# 文件: configs/synthesis_config.yaml (V3.0 - 精确ROI锚点版)

# --- 1. 核心生成参数 ---
num_images_to_generate: 10000  # 为稀缺类别生成充足的数据
output_image_size: [800, 600]

# --- 2. 战斗单位合成参数 ---
unit_density:
  min_enemy_units: 3
  max_enemy_units: 10
  # 友方单位固定为1个玩家+1个宠物

# --- 3. 【核心更新】高保真放置黄金法则 (基于您的精确ROI) ---
placement_rules:
  # 战术槽位ROI：每个单位将在其指定的矩形框内随机放置
  formation_slots:
    enemy_back:
      - [30, 187, 130, 282]
      - [111, 145, 207, 240]
      - [144, 46, 303, 192]
      - [254, 43, 364, 138]
      - [320, 13, 453, 111]
    enemy_front:
      - [83, 261, 202, 359]
      - [148, 180, 272, 295]
      - [238, 147, 356, 253]
      - [311, 81, 428, 203]
      - [398, 56, 517, 161]
    friendly_front: # For pets
      - [304, 394, 406, 497]
      - [366, 343, 474, 442]
      - [441, 288, 553, 387]
      - [512, 237, 621, 346]
      - [578, 185, 703, 290]
    friendly_back:  # For players
      - [375, 412, 472, 556]
      - [438, 364, 546, 517]
      - [513, 313, 616, 446]
      - [596, 270, 707, 413]
      - [666, 223, 766, 363]
  
  overlap_threshold: 0.05 # 允许的重叠率可以调得更低，因为位置已经很精确

# --- 4. 状态指示器关联规则 (精确版) ---
healthbar_association:
  enabled: true
  probability: 0.95
  vertical_offset: -30 # 固定向上偏移30像素
  body_center_jitter_ratio: 0.4
  
damage_number_association:
  enabled: true
  probability: 0.7

# --- 5. UI遮挡增强 (精确版) ---
ui_occlusion:
  enabled: true
  probability: 0.5
  # 技能UI背景的绝对位置
  panel_roi: [303, 135, 495, 463]
  # 技能图标相对于 panel_roi 左上角的偏移位置
  skill_slots_relative:
    - [30, 42, 69, 77]
    - [124, 40, 164, 79]
    - [29, 87, 70, 127]
    - [124, 85, 162, 125]
    - [29, 131, 71, 170]
    - [122, 130, 163, 173]
  num_skills_to_show_range: [4, 6]

# --- 6. 资产约定 (保持不变) ---
asset_conventions:
  default_facing_direction: "right"